### PR TITLE
update hu.ts files

### PR DESCRIPTION
**Pull request by attuska**

### CODE REVIEW

**Comment by pmattern** [comment]
In `pcmanfm-qt_hu.ts` several strings are missing in contexts MainWindow and PreferencesDialog.

Fixing should be rather easy by editing and making another commit basically as usual but invoking `git commit --amend`. If you don't change the commit message this should just merge the new modifications into attuska/pcmanfm-qt@5a471db and you can then update this PR by running `git push --force origin master:master` (assuming you made your local clone by running `git clone https://github.com/attuska/pcmanfm-qt.git`).

**Comment by attuska** [comment]
I think, I did it. Thank you for your help. ( git push --amend, git push --force origin master:master) 
In my repository in contexts MainWindow, and PreferencesDialog the strings are already translated.
https://github.com/attuska/pcmanfm-qt/blob/master/pcmanfm/translations/pcmanfm-qt_hu.ts

But is invisible in PR. Huhhh.

(Google translated)

**Comment by attuska** [comment]
Finally it has succeeded.

git add pcmanfm/translations/pcmanfm-qt_hu.ts
git push --amend
git push --force origin master:master

**Comment by pmattern** [comment]
Translators' comments should be in English.
As for Git this should be fixable just by repeating the steps you rightly posted in your last comment.

Regarding the translation itself I have to admit you got me a bit baffled right now.
On the one hand you've been posting translations for months and to my knowledge there have never been any complaints besides other Hungarian users are definitely around. But in some of your last comments you keep mentioning that you make use of Google translate.
I really don't mean to offend you but please understand that the use of Google translate to post comments rises the question about the quality of a translation. Or are you by any chance adapting the German translations as you seem to speak German very well?

**Comment by attuska** [comment]
Meine Überzetzungen haben sich bissher in der Praxis gut gewahrt, ich prüfe sie in der Praxis. Ich muss es wieder feststellen, dass meine Muttersprache ungarisch sei. Mit der deutschen Sprache bin ich sehr vertraut, und ich prüfe meine Übersetzungen gegen die deutschen auch.
Die englische Sprache beherrsche ich wirklich nicht, aber was die sogenannten Computersprache betrifft, weiss ich fast alles.
Wenn du diese Übersetzung übernimmst, dann werde ich mich freuen, wen nicht, dann werde ich ein bischen traurig, und werden die andere Distributionen  (Arch-Linux, UBUNTU, etc.)  auf einen anderen Übersetzer warten. Allerdings, in der distribution UHU-Linux werden meine Übersetzungen übergehen in form von Patches.
Und wenn es enen anderen ungarischen Übersetzer gabe, dem stehe ich Ihm überhaupt nicht im Wege, sonern würde ich mich darüber sehr freuen.
Übrigens ich bin schon 63 jahre alt, und werde im Englisch schon nie perfect sein.

Google..
My translations have been well respected in practice, I will test it in practice. I need to find again that my native language is Hungarian. With the German language, I am very familiar, and I check my translations from the German also.
The English language I really do not speak, but with regard to the so-called computer language, I know almost everything.
If you take this translation, then I will be happy who do not, then I'll be a little sad, and the other distributions (Arch Linux, Ubuntu, etc.) are waiting for another translator. However, in the distribution UHU-Linux my translations will pass in the form of patches.
And if it gift enes other Hungarian translator, which I did not stand in his way, I would be happy about sonern very.
Incidentally, I am already 63 years old, and will never be perfect already in english.

**Comment by pmattern** [comment]
Alright. Please be assured that I'll be pleased to go on merging your much appreciated contributions then!

Any chance you could nevertheless modify the `<translatorcomment>` stuff as written in my previous comment?

**Comment by attuska** [comment]
The things <translation comment> I think are keep to myself, and are good in Hungarian, do not need to appear in English.
These sections are to translate superfluous, the Hungarian users that are already understand without translating.

**Comment by attuska** [comment]
Bye!
https://github.com/uhulinux/ub/commit/44abcf45ec3c2b0bccfd829f4bac77ed39be06ce
I close my PR, and delete my fork.

**Pull request closed without merging**
