### PR TITLE
Update libfm-qt Russian translation and small fix of pcmanfm-qt trans…

### PR DESCRIPTION
**Pull request by Ilya87**
…lation

### CODE REVIEW

**Comment by pmattern** [comment]
Any particular reason why you left those strings in`libfm-qt/translations/libfm-qt_ru[_RU].ts`, context "RenameDialog" and `pcmanfm/translations/pcmanfm-qt_ru[_RU].ts`, context "AboutDialog" untranslated?

**Comment by Ilya87** [comment]
1 - RenameDialog - They are never translated. In my opinion they are marked not right as translatable strings. dest, dest file info, src are always replaced by actual values of filename, path, etc.
screen

2 - Untranslated string in AboutDialog contains only License. And I don't think it is really needed to be translated.

**Comment by pmattern** [comment]
→ libfm
You seem to be right, yes. This can definitely be left as is for now, you may even consider filing an issue to get the translation strings removed.

→ pcmanfm
This doesn't provide the license itself but some kind of short introduction into the legal situation of the software. Providing information like this in native languages does make sense in my opinion which at a glance seems to be shared by the majority of translators.
So no, this should be translated.

**Comment by Ilya87** [comment]
I think now all is done.

**Comment by pmattern** [comment]
So do I.
As you'll probably understand I had to adjust the commit message - stuff like "(part 2)" doesn't make sense in upstream master.
Thanks!

**Pull request closed without merging**
