### PR TITLE
Italian translation update

### PR DESCRIPTION
**Pull request by smart2128**

### CODE REVIEW

**Comment by PCMan** [comment]
Thank you for the PR.
However the ts file you provided contains errors.
Please check line 96 of pcmanfm-qt_it.ts.

**Comment by smart2128** [comment]
I fixed and committed it.
If you prefer, I can close this pull request and reopen it as soon as I'll be able to squash commits.

**Comment by pmattern** [comment]
@smart2128 
For the time being we can squash on behalf of you to save the hazzle. This can be done in a way that preservers your authorship, see example [here](https://github.com/pmattern/pcmanfm-qt/commits/master).

@PCMan 
Would you agree?

Aside from this I'd be curious to know where those lines `<<<<<<< HEAD` came from. Die you use some particular tool?

**Comment by smart2128** [comment]
@pmattern Thank you. I'm also trying to find what added those lines. I used Qt Linguist to edit the file and git CLI to squash and commit.
I think my squashes failed because I was missing the --force git push flag.
I would thank you both of you for the support.

**Comment by PCMan** [comment]
@pmattern Yes of course.  Please do it. :-)

**Comment by smart2128** [comment]
Aren't they squashed now?

**Comment by pmattern** [comment]
@smart2128 
Yes, the two commits got squashed in the meantime. Maybe PCMan missed this while writing his last comment as they hadn't been squashed before.
So your translations landed in acf75fe.
Thanks for contributing.

**Pull request closed without merging**
