### PR TITLE
DesktopWindow: Render tilled wallpaper manually

### PR DESCRIPTION
**Pull request by palinek**
Fixes tiling of wallpapers after https://github.com/lxde/pcmanfm-qt/commit/de24628202b2789d8c11954669a5b86f35b2c346.

### CODE REVIEW

**Comment by tsujan** [comment]
OK. I tested this with a 200x150 image and a 1920x1080 screen and couldn't see any difference in CPU usage. Apparently Qt devs have exaggerated about the efficiency of `drawTiledPixmap()` ;)

IMO, it's better to wait for a week and then merge it in case there's no feedback.

**Comment by tsujan** [comment]
The question arises as to why not doing a similar thing with `WallpaperStretch` too? I mean:
````
    ...
    else if(wallpaperMode_ == WallpaperStretch) {
      const QSize s = size();
      pixmap = QPixmap(s);
      QPainter painter(&pixmap);
      image = loadWallpaperFile(s);
      painter.drawImage(0, 0, image);
    }
    ...
````
In this way, `paintBackground()` would only draw an empty pixmap, which seems better because paintBackground()` is called frequently. I think that should work with dual monitors too but I can't test.

**Comment by palinek** [comment]
> The question arises as to why not doing a similar thing with WallpaperStretch too? I mean:

Why would we do that? Isn't the `QPixmap::fromImage` good for some reason?

> In this way, paintBackground() would only draw an empty pixmap,

Empty pixmap?

**Comment by tsujan** [comment]
Never mind! I was working on two different things at the same time; hence those words, which are strange to me too ;)

**Comment by foxpup** [comment]
I thought I'd jump in with my observations here.  I am running the latest version of lxqt at least as late as the repositories update to. (0.11.1 on ubuntu zesty)  I'm also running three 4K monitors in panoramic wide mode. (11520x2160) Until recently I was unable to span an image that big across the entire panorama, but it now works.  Strangely, repeated tiling of smaller images does not.  I only get the one image in the upper left corner of the leftmost monitor.  This used to work but is now broken. Overall this is progress since I simply need to generate a 11520x2160 jpg file with any desired content to get whatever look I want and I wasn't able to do that before.  That said, I'm sure others would like to see the repeating tile feature working again.  I am willing to try things and report the effects on my system.  It is my main system so I don't want to do things that are too extreme but I'm willing to do minor stuff and report the results.  (also, I'm using an ASUS NVidea G-Force GTX 960 -  370.28 driver - pushing out to three Dell P2815Q 30Hz 4k monitors)

**Comment by palinek** [comment]
> Strangely, repeated tiling of smaller images does not. I only get the one image in the upper left corner of the leftmost monitor. This used to work but is now broken.

Yes, this is the problem, we are trying to solve here.

**Comment by tsujan** [comment]
> It is my main system so I don't want to do things that are too extreme but I'm willing to do minor stuff and report the results

If you can compile from the source, please tell us whether https://github.com/lxde/pcmanfm-qt/tree/tiled_wallpaper2 fixes the tiling issue with your gigantic display and without any extra CPU usage!

**Comment by palinek** [comment]
@tsujan @PCMan how about this?

**Comment by tsujan** [comment]
@palinek 
Oh, we forgot this. Merge it!

**Pull request merged**
