### PR TITLE
Update translations source files (*.ts)

### PR DESCRIPTION
**Pull request by rbazaud**
see PR #266

### CODE REVIEW

**Comment by jleclanche** [comment]
@rbazaud This is done once every release. Any reason why you want to do it now?

**Comment by rbazaud** [comment]
Mmh, I didn't know that. I was working on French translation, but it appears many strings I've translated are in fact labeled as «vanished», which is why someone told me it would probably be best to «synchronize» it… Does it count as a valid or legitimate reason ?

**Comment by pmattern** [comment]
There's a bunch of problems due to TS files being handled like they are right now.
Translations that have already been made may get lost or strings may get tagged `type="unfinished"` for apparently no reason, e. g. compare latest version of `pcmanfm-qt_de.ts` in lxde/pcmanfm-qt@8806913 with the one from lxde/pcmanfm-qt@d555e13 where everything had been complete.
The preview of UIs to get translated in QtLinguist sometimes stops working as QtLinguist cannot find the corresponding source files.
Also, diffing the untranslated template (?) TS files like `pcmanfm-qt.ts` with translated counterparts, which still makes sense at times besides tools like QtLinguist are normally used, is frequently pretty much impossible as the order of strings is different on a regular basis.

Of course there are very good reasons to wait for string freezes or releases to update the TS files and I for one don't know how to do better. But nevertheless the current proceeding represents a massive hindrance for people who want to contribute by translating right now (not talking about the lack of something like Pootle but about the problems stated above). And those people have time to do so right now. We cannot expect them to still have time once we're really ready to accept translations.
Also, when using VCS checkouts on production systems it's of course more convenient to have translations at hand.

On a side note people lots of PRs featuring updates of TS files have been accepted frequently already. Problem had been touched in lxde/lxqt#693, too.

**Comment by PCMan** [comment]
Better to update these strings at once before release. But indeed, this create problems for the translators. Shouldn't we just use pootle or something else to manage the translations?

**Comment by PCMan** [comment]
So, I'd say, let's don't touch the *.ts files right now. Let's update them all at once before the next release, which I believe is coming soon since several important bugs are fixed recently.

**Pull request closed without merging**
