### PR TITLE
build: Use external translations

### PR DESCRIPTION
**Pull request by palinek**
Also use the lxqt_translate_ts/lxqt_translate_desktop from the liblxqt.
But this is only a build dependency, no lxqt component is needed in runtime.

### CODE REVIEW

**Comment by agaida** [comment]
Tested and GTM

**Comment by paulolieuthier** [comment]
I think we should wait for more opinions here (ping @PCMan). PCManFM (and QTerminal also), while part of LXDE, doesn't follow the exactly same path regarding dependencies and other things.

**Comment by PCMan** [comment]
Busy working on my master thesis and don't have much time for this ATM, but I trust the judgement and programming skills of you guys. :-)  So as long as it's tested and proved to be working, please go ahead.
Cheers!

**Comment by palinek** [comment]
> wait for more opinions here. PCManFM (and QTerminal also)

Huh... qterminal was already updated to use the external translations...

**Comment by palinek** [comment]
>  but I trust the judgement and programming skills of you guys. :-)

merging..

**Pull request merged**
