### PR TITLE
Put tabbar right above the folder-view.

### PR DESCRIPTION
**Pull request by tsujan**
Just a simple layout change. The previous position of tabs, above the left pane, seemed a little counterintuitive.

### CODE REVIEW

**Comment by PCMan** [comment]
No, this is done by design.
1. This can contain more tabs in the same window width.
2. Firefox has similar layout.
3. We've been using this in old gtk+ version of pcmanfm and no users complain of that.

**Comment by PCMan** [comment]
However, if this is optional and is turned off by default, I'm happy to include it.

**Comment by pmattern** [comment]
Besides I didn't open an issue yet something I'd love to see is being able to make the choice between Directory Tree and Places view not per window as right now but per tab. This is something I figure would be very useful, in particular as long as #144 isn't addressed. But if selecting the view mode per tab should ever get implemented the current placement of tabs would still make more sense.
Regarding the current behaviour to have the same kind of view in all tabs of a window I agree that the layout proposed by this PR is definitely better.
So all in all I agree with @PCMan that this new feature should somehow be made optional.

**Comment by tsujan** [comment]
@PCMan
This change of layout doesn't seem so important to me. I used Qt styles with centered tabs since I came to LXQT. Once I applied a style with left-aligned tabs, I found the current layout somehow odd and also aesthetically unappealing. However:

> This can contain more tabs in the same window width.

Most screens are wide enough nowadays. Moreover, tab scroll buttons and "tab tear" automatically appear when needed (I've never seen them with PCManFM although I usually open multiple tabs).

> Firefox has similar layout.

It could be also said that Dolphin has a layout similar to this PR.

> We've been using this in old gtk+ version of pcmanfm

That's just a matter of habit. Perhaps, my point is so too ;)

**Comment by PCMan** [comment]
@tsujan Would you please make this feature optional?

**Comment by tsujan** [comment]
@PCMan Sure!

**Comment by tsujan** [comment]
@PCMan 
Done at https://github.com/lxde/pcmanfm-qt/pull/323 !
Please close this PR if you prefer https://github.com/lxde/pcmanfm-qt/pull/323 over it.

**Comment by PCMan** [comment]
Yes, let's fix this there.

**Pull request closed without merging**
