### PR TITLE
GUI to change desktop directory in Desktop preferences

### LINKED ISSUE #46: Add GUI to change desktop dir in Desktop Preferences
This should change XDG_DESKTOP_DIR which defaults to ~/Desktop if not specified.

### PR DESCRIPTION
**Pull request by paulolieuthier**
Fixes #46 and adds new dependency on libqtxdg.

### CODE REVIEW

**Comment by jleclanche** [comment]
lgtm

**Comment by luis-pereira** [comment]
gtm

**Comment by jleclanche** [comment]
@paulolieuthier I can't merge this, it's not finding the branch... can you do pull requests from your own forks if possible?

**Comment by jleclanche** [comment]
@paulolieuthier I'll let you merge it into master

**Pull request merged**
