### PR TITLE
- Bump cpack versioning

### PR DESCRIPTION
**Pull request by heliocastro**

### CODE REVIEW

**Comment by jleclanche** [comment]
This should go away, we depend on liblxqt already

**Comment by luis-pereira** [comment]
@jleclanche actually we don't.

**Comment by jleclanche** [comment]
Hmm, this is hard to justify. I'll think about it.

**Comment by luis-pereira** [comment]
@jleclanche Not sure what you meant. pcmanfm-qt doesn't depend on liblxqt in any way that I know of.

**Comment by jleclanche** [comment]
You can merge this for now, it doesnt matter.

**Comment by luis-pereira** [comment]
@jleclanche I won't. The version is hardcoded in two distintt places:
https://github.com/lxde/pcmanfm-qt/blob/master/CMakeLists.txt#L4
https://github.com/lxde/pcmanfm-qt/blob/master/CMakeLists.txt#L92

**Comment by luis-pereira** [comment]
Superseded by 7aec9da0dfbdbc0d77f171a4e000de19b4fecdae

**Pull request closed without merging**
