### PR TITLE
Set quit shortcut from the ui file

### PR DESCRIPTION
**Pull request by npmiller**
See discussion in: https://github.com/lxde/pcmanfm-qt/pull/307

### CODE REVIEW

**Comment by excalibur1234** [comment]
thank you to the whole team for all the latest pull requests!
i am sure they will improve usability of pcmanfm-qt noticeably.

**Comment by palinek** [comment]
GTM

**Comment by pmattern** [comment]
GTM. Works as expected.

**Comment by PCMan** [comment]
Merged. Thank you.

**Pull request closed without merging**
