### PR TITLE
Handle cmake cmp0071

### PR DESCRIPTION
**Pull request by luis-pereira**

### CODE REVIEW

**Comment by luis-pereira** [comment]
Part of the fix to https://github.com/lxde/lxqt/issues/1420

**Comment by tsujan** [comment]
I don't know the story behind `SKIP_AUTOGEN` but this works as intended.

**Comment by tsujan** [comment]
We already have a policy conditional for CMP0063. Doesn't another one for CMP0071 work?

**Comment by luis-pereira** [comment]
@tsujan 
`SKIP_AUTOGEN` works fine, I know. I expected that it woudn't be needed.
The documentation says that:
> If any of the files should be  processed, set CMP0071 to NEW.

But none of our files should be processed. They were already processed. Setting CMP0071 to NEW will apply to all files. We don't want that.

CMP0063 is a different case. We want the NEW policy to be applied. The OLD policy was not what we wanted anyway.

**Comment by tsujan** [comment]
@luis-pereira I'm not good at cmake. Thanks for the explanation!

**Comment by luis-pereira** [comment]
By the way ```CMP0063``` should not be there. It's set in `LXQtCompilerSettings` module. It's an artifact from the times when `pcmanfm-qt` did not use `lxqt-build-tools`. Adressed in https://github.com/lxde/pcmanfm-qt/pull/610.

**Comment by agaida** [comment]
GTM

**Pull request merged**
