### PR TITLE
Multihead Wallpaper support

### PR DESCRIPTION
**Pull request by pakdel**
It is a simple implimentation and does not center or resize.

### CODE REVIEW

**Comment by jleclanche** [comment]
What does it actually do? "Multihead" is not exactly descriptive.

**Comment by pakdel** [comment]
I simply wanted to be able to set a large wallpaper for my multihead configuration, and have it properly split and span all my displays.
For example, if you have three 1920 × 1080 monitors and you use Xinerama with a horizontal layout, it results in a 1920 × 3240 desktop, so you should be able to set a big 1920 × 3240 panorama picture as your wallpaper and see it properly divided into three 1920 × 1080 segments and set from left to right on your X screen root windows, which results in something that looks like the original picture.

**Comment by jleclanche** [comment]
@pakdel I'm sorry nobody got to this sooner. Could you make this option only show up in the UI when the user either already has it selected, or has more than one screen?

**Comment by pakdel** [comment]
Sure. I do not have any multihead setup around until Monday, so I will start then.

**Comment by jleclanche** [comment]
@pakdel I'm sorry about the short notice, but letting you know: We're starting a feature freeze in a couple of days, so this will have to land soon if you want it in 0.9. I'd personally like to see it there.

**Comment by pakdel** [comment]
@jleclanche I have made the change you asked for. Let me know if there is anything else.

**Comment by jleclanche** [comment]
@pakdel Im testing it and I don't understand why it's better than "Center on the screen". If you have a wallpaper of the appropriate resolution, it should work fine.

**Comment by pakdel** [comment]
@jleclanche nice catch! Changes that are made (to the work area) since my initial pull request have made my code useless :D

**Comment by pakdel** [comment]
I am closing this.

**Comment by jleclanche** [comment]
Ah, cool. =)

**Pull request closed without merging**
