### PR TITLE
Added shortcut for filterbar.

### PR DESCRIPTION
**Pull request by tsujan**
Also added Ctrl+F, in addition to F3, for the search utility.
This is for https://github.com/lxde/pcmanfm-qt/issues/311.

### CODE REVIEW

**Comment by pmattern** [comment]
tsujan/pcmanfm-qt@43fb282 is not working as expected here:

If the filter bar is already visible (opened) hitting `Ctrl+I` hides (closes) it no matter whether or not it has the focus.

Also, I'm not sure whether it makes sense to state `Ctrl+I` as shortcut at menu View - Filter.
As discussed in https://github.com/lxde/pcmanfm-qt/issues/311#issuecomment-184201291 there are basically two actions involved, making the filter bar (in-) visible (close / open it) and bring the focus into it. Shortcut `Ctrl+I` is primarily meant to set the focus. In addition it's opening the filter bar should the latter be closed when the shortcut gets hit which makes perfect sense. But the shortcut is not really meant to hide the filter bar, is it? Therefore it's wrong to state it next to topic "Filter" in menu "View".

(Shortcut `Ctrl+F` is opening the search toll without preventing `F3` from doing the same which is both expected behaviour.)

**Comment by tsujan** [comment]
@pmattern Thanks for testing!

Oh, you want the exact behavior of Dolphin while I thought in this way: the user may want to hide/show the filterbar so that when it's shown, it gets focus and when it's hidden, the focus returns to the folderview.

As I said earlier, I see no reason to imitate Dolphin or any other file-manager to such an extent but if others want it too, why not? It's just a matter of a few additions and changes. Let's wait for another vote ;)

**Comment by tsujan** [comment]
@pmattern
OK, I supposed that @palinek was on your side and made some changes. Is it now what you had in mind?

**Comment by palinek** [comment]
To be correct, I wasn't aware that the filter bar is hidable at all (I use pcmanfm-qt very sporadically).

Just tested and it's OK for me. (just missing the Esc shortcut, but that's the different PR)

GTM

**Comment by pmattern** [comment]
Imitating or not imitating some other file manger isn't a concern for me (in fact I even don't like Dolphin at all). I'm just trying to think about what makes sense and what doesn't.
Regarding `Ctrl+I` I was just thinking that it should *always* bring the focus to the filter bar, not just if the bar happens to be closed, which is implemented now.
You even added a shortcut `Ctrl+B` to open/close the filter bar which is something I'd consider optional as said before but which sure doesn't hurt.

All in all definitely GTM from my side, too.

**Comment by tsujan** [comment]
@pmattern 
Thanks! Surely I got your point *(keyboard-only use)* when I added `Ctrl+I` and especially afterward, when I used it. Good things could come up when the two sides of a dialog have different or opposite opinions -- like what happened here.

**Comment by tsujan** [comment]
When the filterbar is closed (made hidden), the filter strings should be cleared for ALL tabs. That's about an old bug, which is now fixed by this commit too.

**Comment by PCMan** [comment]
LGTM, but there is one problem. Ctrl+I is reserved for invert selection in old gtk+ version of PCManFM and I forgot to add this shortcut to the Qt version.
If we're going to keep the old behavour of the gtk+ version, it's better to use something other than Ctrl+I for the filter bar. However, I'm OK to change it if more users want Ctrl+I for the filter bar instead.

**Comment by pmattern** [comment]
Given that Dolphin is using `Ctrl+I` for the filter bar as well I'd personally tend to say let's use it, too, even if this is inconsistent with the GTK flavour's behaviour.

**Comment by PCMan** [comment]
Merged. Thanks!

**Pull request closed without merging**
