### PR TITLE
Paste into the folder when using its context menu for pasting.

### PR DESCRIPTION
**Pull request by tsujan**
When a single folder is right clicked and the "Paste" item on its context menu is used, the copied/cut items aren't pasted into it but into the currently open folder (containing it). This commit makes them be pasted into the right clicked folder.

If MULTIPLE folders/files are right clicked, the copied/cut items will be pasted into the currently open folder, as before.

### CODE REVIEW

**Comment by tsujan** [comment]
I'm a little confused. m

**Comment by paulolieuthier** [comment]
@tsujan that's because you are using your master branch. One should always create a new branch for new PRs. That way he can push more commits until the PR is ready.

**Comment by palinek** [comment]
> I'm a little confused. m

You named this PR *Paste into the folder when using its context menu for pasting.*. So IMO commit a361a10 doesn't belong here.

If you prefer to create a bunch of (unrelated) commits adding/fixing (unrelated) features/issues, name the PR more universaly and try to describe every change in comment... but this way it will probably take longer to review and pull the whole batch.

**Comment by tsujan** [comment]
@paulolieuthier Thanks! I should read the doc thoroughly. @palinek You're right, the second commit doesn't belong here. Thanks!

**Comment by tsujan** [comment]
OK, one PR per branch. Sorry for my ignorance! For my next PR's I'll make new branches.

Could you please make an exception in this case and consider the second commit here too? Although it isn't directly related to the first one, it's simple.

**Comment by paulolieuthier** [comment]
Hey, don't worry, it's cool.

**Comment by tsujan** [comment]
I close this PR because it got so messy! I'll add clean ones soon.

**Pull request closed without merging**
