### PR TITLE
Fixes two typos

### PR DESCRIPTION
**Pull request by tsujan**
On of them was old; the other was made recently (which commit?)

### CODE REVIEW

**Comment by tsujan** [comment]
Could someone confirm that `%1` was changed to `%n` by mistake? It was `%1` originally.

**Comment by paulolieuthier** [comment]
GTM.

**Comment by tsujan** [comment]
@paulolieuthier
It was https://github.com/lxde/pcmanfm-qt/commit/537bfc2b904fd9520fbb23f77a24e1bfb64bbb9d. `tr()` was changed to plural but the argument wasn't removed. Am I right?

**Comment by paulolieuthier** [comment]
I wasn't sure about that, but after reading http://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals, I'm sure you are right.

**Comment by tsujan** [comment]
> I wasn't sure about that, but after reading http://doc.qt.io/qt-5/i18n-source-translation.html#handling-plurals, I'm sure you are right.

Yes, that was exactly what I read too because I wasn't sure either ;)

**Pull request merged**
