### PR TITLE
Add GUI to change desktop dir in Desktop preferences. Fixes #46.

### LINKED ISSUE #46: Add GUI to change desktop dir in Desktop Preferences
This should change XDG_DESKTOP_DIR which defaults to ~/Desktop if not specified.

### PR DESCRIPTION
**Pull request by paulolieuthier**

### CODE REVIEW

**Comment by jleclanche** [comment]
@paulolieuthier i take it this wont land before 0.9?

**Comment by paulolieuthier** [comment]
It was ready, but there was no agreement on merging, that's all.

**Comment by jleclanche** [comment]
@paulolieuthier A good first step is adding an interface for it in libqtxdg because it should have it anyway. Then we can rediscuss putting this in pcmanfm-qt.

Delayed until 1.0.

**Comment by jleclanche** [comment]
Note that if we do this, I'd really like to see it added to libqtxdg before 0.9 though.

**Comment by paulolieuthier** [comment]
@jleclanche you mean a standalone application in liblxqt for that? It sounds weird, as it's only a library. IHMO, that should go with the application that paints the desktop background and the icons, or in lxqt-config.

**Comment by jleclanche** [comment]
No, I meant the functionality to get/set desktop dir should be added to
libqtxdg before 0.9 is released

**Comment by paulolieuthier** [comment]
That was done in lxde/libqtxdg#20, back when I created this PR.

**Comment by PCMan** [comment]
Assign this to me.
I'll start handling file manager related issues after my final exam.
Thanks.

**Comment by jleclanche** [comment]
Oops, sorry, didn't see. Well done.

**Comment by luis-pereira** [comment]
@jleclanche libqtxdg already has the code. It got merged. Check lxde/libqtxdg@0d80985769ab05691ab3c8768ca63f7b6c74feb4
 What's missing is actually the Ui.

**Comment by paulolieuthier** [comment]
I'll create a new PR for this, as this one was made from an old repository that was deleted. Github offers a patch, but I'll still have to rebase it.

**Comment by luis-pereira** [comment]
@paulolieuthier Are you talking about libqtxdg or pcmanfm-qt ?

**Comment by paulolieuthier** [comment]
@luis-pereira: pcmanfm-qt. I'll be sending a PR in a few minutes.

**Comment by paulolieuthier** [comment]
#117

**Pull request closed without merging**
