### PR TITLE
move config to /usr/share/pcmanfm-qt/lxqt

### PR DESCRIPTION
**Pull request by agaida**

### CODE REVIEW

**Comment by tsujan** [comment]
GTM.

**Comment by palinek** [comment]
While at it.... the handling of settings in pcmanfm-qt is IMO wrong -> https://github.com/lxde/pcmanfm-qt/blob/master/pcmanfm/settings.cpp#L149

We are trying to do by hand (and not fully compatible) the very same as the `QSettings` (properly used) does provide by itself.

**Comment by tsujan** [comment]
> ... the handling of settings in pcmanfm-qt is IMO wrong...

It's not wrong but I agree that it might be better to rely on QSettings.

**Comment by palinek** [comment]
> It's not wrong but I agree that it might be better to rely on QSettings.

By "wrong" I meant unneeded manual processing and not fully compatible (it loads the keys/values **only** from the first file found, not considering other existing files which may contain other key/value pairs).

**Comment by tsujan** [comment]
I know and, as told above, I agree with you -- the word "wrong" just had an extra connotation.

**Pull request merged**
