### PR TITLE
Desktop folder

### PR DESCRIPTION
**Pull request by luis-pereira**
Should go with https://github.com/lxde/lxqt-session/pull/39
Discussion [here](https://github.com/lxde/lxqt/issues/780)

@PCMan This is your call.

### CODE REVIEW

**Comment by PCMan** [comment]
Really thank you for the hard work. The change looks pretty good.
One little thing, though. Instead of turning this off at compile time, would it be better to enable the desktop folder editing feature at runtime? For example, it's easy to check the existence of lxqt-session dbus service, so we can know whether we're  running in LXQt session and need to hide the option. Otherwise, show the desktop folder editing option to the user. What do you think?

**Comment by luis-pereira** [comment]
@PCMan I considered that aproach. I choosed this one for size optimization.

In an somehow related issue: What's your opinion about splitting pcmanfm-qt into two:
* pcmanfm-qt 
* desktop manager

**Comment by luis-pereira** [comment]
@PCMan that would tie to LXQt, have you considered that ?

**Comment by jleclanche** [comment]
@luis-pereira There's quite a bit of an advantage to have the desktop being managed by the file manager. Both windows and gnome do it this way.

**Comment by jleclanche** [comment]
@luis-pereira so I'm not a fan of this approach at all. As I said before, it's OK to have two places where this stuff is configured - however of course they should use the *same* method for configuring it.

323baa58b4ee1307dc76cabc891cf94958106857 can be landed right away btw.

**Comment by luis-pereira** [comment]
@jleclanche There's no point in landing https://github.com/lxde/pcmanfm-qt/commit/323baa58b4ee1307dc76cabc891cf94958106857 without the rest. What advantages do you refer to ?

By detecting LXQt session we tie pcmanfm-qt to LXQt. I will update the code.

**Comment by luis-pereira** [comment]
@jleclanche @PCMan Updated

**Comment by PCMan** [comment]
@luis-pereira  Sorry for the late reply. I don't have time for coding this month. :-(
About the idea of splitting the desktop manager part from the file manager, I'd say it might be better to leave it as it is. If you split them into two processes, the folder caches, icon caches, and other caches, which are heavily used, cannot be shared among them. This hurts both performance and memory usage. Besides, opening a folder is such a frequently done operation for a normal GUI user, so it's good to keep running the file manager in the background for fast startup. Since the desktop manager is running all the time, it does the job and we don't need a separate daemon. Moreover, the desktop manager is just a specialized folder view of pcmanfm-qt with its background painted with the wallpaper. So this achieve maximized reuse of existing code.
Give the merits mentioned above, I'd suggest leave it as it is and do not do the split.

**Comment by luis-pereira** [comment]
@PCMan I was thinking in people that don't uses pcmanfm-qt file manager. For the ones who use it, I do agree with you.
This PR now detected LXQt and disables the Edit Desktop Folder and enables a watcher for changes.

**Comment by PCMan** [comment]
@luis-pereira: Then it's possible to split it into two modules, which are loaded into the same process. For those who only want the desktop manager, they can install that module only. This does not save much, though. The desktop manager is just a specialized file manager window without window decoration and menu. For those who don't need desktop icons, it's safe to uninstall pcmanfm-qt and use whatever tool they want to set a nice wallpaper.
BTW, I'm currently handling this PR. Thank you for the effort.
I'd merge it soon.

**Comment by PCMan** [comment]
Merged. Thanks!

**Pull request closed without merging**
