### PR TITLE
Let the style engine draw the text selection rect on desktop.

### PR DESCRIPTION
**Pull request by tsujan**
The same as https://github.com/lxde/libfm-qt/pull/11 but for desktop (as was promised).

### CODE REVIEW

**Comment by tsujan** [comment]
Please consider this PR because I want to make a *clean* PR (to fix desktop bottom gap) that also changes `desktopitemdelegate.cpp`. Thanks in advance!

**Comment by paulolieuthier** [comment]
GTM.

**Comment by palinek** [comment]
As it is the same as in lxde/libfm-qt#11, @tsujan go ahead and merge it.

**Comment by tsujan** [comment]
@palinek , @paulolieuthier  Thanks!

**Pull request merged**
