### PR TITLE
Add quit shortcut

### PR DESCRIPTION
**Pull request by npmiller**

### CODE REVIEW

**Comment by palinek** [comment]
GTM

**Comment by paulolieuthier** [comment]
GTM.

**Comment by PCMan** [comment]
@palinek @paulolieuthier Thank you for reviewing this.
If you see this kind of little patches which are apparently LGTM, it might be a good idea to just merge them directly? :-)

**Comment by PCMan** [comment]
Merged.

**Comment by pmattern** [comment]
Now that the new shortcut is available, wouldn't it make sense to mention it in menu "File"?
If I'm not mistaken best as `Ctrl+Q` next to "Close Window" much as `Ctrl+W` is already next to "Close Tab" right now   

pcmanfm-qt_missing-ctrl q

**Comment by tsujan** [comment]
> wouldn't it make sense to mention it in menu "File"?

Yes, it does, of course! As a mouse user, I was encouraged by the recent PR's to use the keyboard more and I naturally pressed Ctrl+Q without knowing it wasn't there before.

**Comment by tsujan** [comment]
But then, it should be put in `main-win.ui` instead of `mainwindow.cpp`.

**Comment by npmiller** [comment]
Is that better: https://github.com/lxde/pcmanfm-qt/pull/315 ?

**Comment by tsujan** [comment]
@npmiller  Yes!

**Pull request closed without merging**
