### PR TITLE
Mousenavigation

### PR DESCRIPTION
**Pull request by qsodev**
fixed url update on mouse back/forward buttons by forwarding signals to MainWindow

### CODE REVIEW

**Comment by palinek** [comment]
After squashing the commits.... GTM

**Comment by jleclanche** [comment]
@palinek I think this would be good to have in 0.10. Author probably didn't understand what was asked of them. I'll try to land it.

**Comment by jleclanche** [comment]
OK nvm, I see this landed and was followed up in #233. But one of the commits didn't land, I'll fix that.

**Comment by palinek** [comment]
@jleclanche I thought everything with this back/forward was landed....

**Comment by jleclanche** [comment]
You're right, actually.

**Comment by qsodev** [comment]
Yes everything is already in master branch and is working fine so far.

**Pull request closed without merging**
