### PR TITLE
mouse navigation url update fix

### PR DESCRIPTION
**Pull request by qsodev**
fixed url update during mouse navigation. 
replaces #232 with clean commit :)

### CODE REVIEW

**Comment by palinek** [comment]
1. Why did you close PR #233 and opened a new one?
2. In this PR there isn't the `void FolderView::childMousePressEvent(QMouseEvent* event)` change (back/forward), is that intentional?

**Comment by qsodev** [comment]
i closed it and made a new one because the history was messed up.
The changes are the same as in #232. I have never changed FolderView::childMousePressEvent(QMouseEvent* event). It is not needed.

**Comment by PCMan** [comment]
Seems that it's a fix for https://github.com/lxde/pcmanfm-qt/commit/b47bd9f46ccb7281f11b9f20040c6741dd2421ac .

**Comment by PCMan** [comment]
merged into master.

**Pull request closed without merging**
